version: 2

models:
  - name: stg_weather_data
    description: "Raw weather data staging model"

  - name: avg_weather_by_location
    description: "Avg weather stats by location"
    columns:
      - name: location
        tests: [not_null]

  - name: daily_avg_temperature
    description: "Daily avg temperature across all locations"
    columns:
      - name: day
        tests: [not_null]
